version: "2" # docker-composeのversion2を使用
services: # 各種サービスの設定

#  memcached:
#    image: memcached
#    container_name: memcached

#  redis:
#    image: redis
#    container_name: redis

  lns-data: # データボリューム用コンテナ、ソースやDBのデータ等開発で生成するものはここにマウント
    build: ./data
    volumes:
      - ../:/data
    container_name: lns-data

  lns-db: # DBストア
    image: mysql:5.6
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci --explicit_defaults_for_timestamp --sql-mode=""
    environment:
      MYSQL_ROOT_PASSWORD: lnsrootpass
      MYSQL_DATABASE: mysql_database
      MYSQL_USER: lns
      MYSQL_PASSWORD: lnspass
      TZ: "Asia/Tokyo"
    ports:
      - "23306:3306"
    volumes_from:
      - lns-data
    volumes:
      - ./mysql/data/:/var/lib/mysql
      - ./mysql/dump/:/dump/
      - ./mysql/init/:/docker-entrypoint-initdb.d/
      - ./mysql/conf/:/etc/mysql/conf.d/
    container_name: lns-db

  lns-fpm: # php-fpm: PHPプロセスを実行するコンテナ
    build: ./fpm
    volumes_from:
      - lns-data
    links:
      - lns-db
#      - memcached
#      - redis
    environment:
      DATABASE_HOST: 'mysql'
      DATABASE_NAME: 'mysql_database'
      DATABASE_USER: 'lns'
      DATABASE_PASSWORD: 'lnspass'
    container_name: lns-fpm

  lns-nginx: # php-fpmにリバースプロキシする
    build: ./nginx
    ports:
      - "20080:80"
    volumes_from:
      - lns-data
    links:
      - lns-fpm
    container_name: lns-nginx

  composer: # composerコマンドを実行するときに都度実行
    build: ./composer
    volumes_from:
      - lns-data
    container_name: lns-composer
